### ISSUE TITLE
spawn ffprobe ENOENT

### ISSUE THREAD

**Issue by almgwary** [insanity54/prevvy#2]
(node:8544) UnhandledPromiseRejectionWarning: Error: spawn ffprobe ENOENT

(node:8544) UnhandledPromiseRejectionWarning: Error: spawn ffprobe ENOENT
    at notFoundError (\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

**Comment by insanity54** [comment]
TY for the issue report. What env are you running in? Is ffprobe in your $PATH?
